# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26ff7a76c0f44aaedc6628832384b363800d5cf6b352d96d0ddd6ea584eb0d48b2fc71f72c57e4ae221847de1cb2a8a4539ec4423cea25f8682f103fdccb656

test:
  secret_key_base: b4349f41e4857410b7507c2036269729d4e315c253a710ceb86ff4a3228b43f2c07da87b86e5445646ce7c58c90bb16f03e4b76bafb24fc5b0bf996aa42fa11e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
